<?php include('header.phtml');?>

<div data-role="page" id="bgf-itempage-<?=$item->hash?>">
	<div data-role="header">
		<h1>Fontana Guide</h1>
	</div>
	<div data-role="content">
		<h2><?=$event->title?></h2>
		<p><small><?=$event->type?></small></p>
		<p><?=$event->description?></p>
		<p><em><?=$event->info?></em></p>
		<ul data-role="listview" data-inset="true" data-theme="c" data-dividertheme="b">
			<li data-role="list-divider">Premietania</li>
			<?foreach($dates as $d):?>
			<li><?=date('d.m.Y o H:i',$d->timestamp).' - '.$WEEKDAYS[date('N',$d->timestamp)]?></li>
			<?endforeach?>
		</ul>
	</div>
	<div data-role="footer">
		<h4>App by<br />BinaryGoo</h4>
	</div>
</div>

<?php include('footer.phtml');?>