<?php include('header.phtml');?>

<div data-role="page" id="bgf-frontpage">
	<div data-role="header" data-nobackbtn="true">
		<h1>Fontana Guide</h1>
	</div>
	<div data-role="content">
		<a href="add_email.php?" data-role="button" data-icon="star">Notifikácie e-mailom</a>
		<br />
		<ul data-role="listview">
		<?foreach($items as $i):?>
			<?if( $curr_date=='' || date('Ymd',$i->timestamp)>$curr_date ):?>
			<?$curr_date=date('Ymd',$i->timestamp);?>
			<li data-role="list-divider"><?=date('d.m.Y',$i->timestamp)?></li>
			<?endif?>
			<li><a href="detail.php?id=<?=$i->hash?>">
				<h5><?=date('H:i',$i->timestamp)?></h5>
				<p><strong><?=$i->title?></strong></p>
				<p><?=$i->type?></p>
			</a></li>
		<?endforeach?>
		</ul>
	</div>
	<div data-role="footer">
		<h4>App by<br />BinaryGoo</h4>
	</div>
</div>

<?php include('footer.phtml');?>