<?php include('header.phtml');?>

<div data-role="page" id="bgf-frontpage">
	<div data-role="header" data-nobackbtn="true">
		<h1>Fontana Guide</h1>
	</div>
	<div data-role="content">
		<a href="add_email.php" data-role="button" data-theme="e" data-icon="star">Notifikácie e-mailom</a>
		<br />
		<ul data-role="listview">
			<li><h3>Aktuálne predstavenia</h3></li>
		<?foreach($dates as $date):?>
			<?if( $curr_date=='' || $date->date>$curr_date ):?>
			<?$curr_date=$date->date;?>
			<li data-role="list-divider"><?=date('d.m.Y',$date->timestamp)?></li>
			<?endif?>
			<li><a href="detail.php?id=<?=$events[$date->event_id]->id?>">
				<h5><?=date('H:i',$date->timestamp)?></h5>
				<p><strong><?=$events[$date->event_id]->title?></strong></p>
				<p><?=$events[$date->event_id]->type?></p>
			</a></li>
		<?endforeach?>
		</ul>
	</div>
	<div data-role="footer">
		<h4>App by<br />BinaryGoo</h4>
	</div>
</div>

<?php include('footer.phtml');?>